apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
